//
//  StudentListDetailsPresenter.swift
//  iOSConfSGDemo
//
//  Created by Danijela Vrzan on 2022-01-10.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StudentListDetailsPresentationLogic
{
  func presentSomething(response: StudentListDetails.Something.Response)
}

class StudentListDetailsPresenter: StudentListDetailsPresentationLogic
{
  weak var viewController: StudentListDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: StudentListDetails.Something.Response)
  {
    let viewModel = StudentListDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
