//
//  StudentListDetailsInteractor.swift
//  iOSConfSGDemo
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

/*
 StudentListDetails files were created via Clean Swift Template as a showcase for the demo
 They have no functionality at all.
 */

import UIKit

protocol StudentListDetailsBusinessLogic
{
  func doSomething(request: StudentListDetails.Something.Request)
}

protocol StudentListDetailsDataStore
{
  //var name: String { get set }
}

class StudentListDetailsInteractor: StudentListDetailsBusinessLogic, StudentListDetailsDataStore
{
  var presenter: StudentListDetailsPresentationLogic?
  var worker: StudentListDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: StudentListDetails.Something.Request)
  {
    worker = StudentListDetailsWorker()
    worker?.doSomeWork()
    
    let response = StudentListDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
