//
//  StudentListDetailsWorker.swift
//  iOSConfSGDemo
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

/*
 StudentListDetails files were created via Clean Swift Template as a showcase for the demo
 They have no functionality at all.
 */

import UIKit

class StudentListDetailsWorker
{
  func doSomeWork()
  {
  }
}
