//
//  StudentListInteractor.swift
//  iOSConfSGDemo
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StudentListBusinessLogic {
  func fetchStudentList() async
}

protocol StudentListDataStore {
  var house: String { get set }
}

class StudentListInteractor: StudentListBusinessLogic, StudentListDataStore {
  var presenter: StudentListPresentationLogic?
  var worker = StudentListNetworkWorker()

  var students: [Student] = []
  var house: String = ""
  let url = "https://hp-api.herokuapp.com/api/characters/house/"
  
  func fetchStudentList() async {
    guard let url = URL(string: url + house) else {
      return
    }
    do {
      students = try await worker.fetchStudents(from: url)
    } catch {
      print(error)
    }
    let response = StudentList.FetchStudentList.Response(students: students)
    presenter?.presentStudentList(response: response)
  }
}
