//
//  StudentListPresenter.swift
//  iOSConfSGDemo
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StudentListPresentationLogic {
  func presentStudentList(response: StudentList.FetchStudentList.Response)
}

class StudentListPresenter: StudentListPresentationLogic {
  weak var viewController: StudentListDisplayLogic?
  
  func presentStudentList(response: StudentList.FetchStudentList.Response) {
    let viewModel = StudentList.FetchStudentList.ViewModel(students: response.students)
    viewController?.displayStudentList(viewModel: viewModel)
  }
}
