//
//  StudentListWorker.swift
//  iOSConfSGDemo
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StudentListNetworkWorker {
  func fetchStudents(from url: URL) async throws -> [Student] {
    let (data, _) = try await URLSession.shared.data(from: url)
    return try JSONDecoder().decode([Student].self, from: data)
  }
}
