//
//  GriffindorListPresenter.swift
//  iOSConfSGDemo
//
//  Created by Danijela Vrzan on 2022-01-06.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GriffindorListPresentationLogic {
  func presentSomething(response: GriffindorList.Something.Response)
}

class GriffindorListPresenter: GriffindorListPresentationLogic {
  weak var viewController: GriffindorListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: GriffindorList.Something.Response) {
    let viewModel = GriffindorList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
